apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archaics

resources:
  - namespace.yaml
  - auth
  - db
  - product
  - payment
  - ai-operator
  - anomaly-detector


secretGenerator:
  - name: archaics-secrets
    literals:
      # Key names MUST match exactly what the deployment env vars reference
      - JWT_SECRET=dummyjwtkey
      - GEMINI_API_KEY=dummygeminikey
      - STRIPE_API_KEY=sk_test_dummy

generatorOptions:
  disableNameSuffixHash: true
